package com.jdevelopstation.l2ce.gui.pane;

import java.awt.Insets;

import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jdevelopstation.l2ce.gui.listeners.window.MenuExitActionListenerImpl;
import com.jdevelopstation.l2ce.gui.listeners.window.MenuOptionsActionListenerImpl;
import com.jdevelopstation.l2ce.utils.BundleUtils;

/**
 * @author VISTALL
 * @date 8:33/28.05.2011
 */
public class MainPane extends JPanel
{
	private JTabbedPane _tabbedPane1;
	private JPanel _panel1;
	private JMenu _mainMenu;

	public MainPane()
	{
		$$$setupUI$$$();

		_mainMenu.setText(BundleUtils.getInstance().getBundle("MainPane.Main"));

		JMenuItem item = new JMenuItem(BundleUtils.getInstance().getBundle("MainPane.Main.Options"));
		item.addActionListener(new MenuOptionsActionListenerImpl());
		_mainMenu.add(item);

		item = new JMenuItem(BundleUtils.getInstance().getBundle("MainPane.Main.Exit"));
		item.addActionListener(new MenuExitActionListenerImpl());
		_mainMenu.add(item);
	}

	private void createUIComponents()
	{
		_panel1 = this;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
		_panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		_tabbedPane1 = new JTabbedPane();
		_panel1.add(_tabbedPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		_tabbedPane1.addTab("*.dat", panel1);
		final DatPane nestedForm1 = new DatPane();
		panel1.add(nestedForm1.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JMenuBar menuBar1 = new JMenuBar();
		menuBar1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		_panel1.add(menuBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		menuBar1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		_mainMenu = new JMenu();
		_mainMenu.setText("Main");
		menuBar1.add(_mainMenu, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return _panel1;
	}
}
